### ISSUE TITLE
Network change

### ISSUE THREAD

**Issue by imprfekt** [StreamFlow-Finance/streamflow-app#19]
Need an option to switch between networks. Currently hardcoded to devnet.
Dropdown for _mainnet, testnet, devnet, local_
OR
Toggle between **mainnet and devnet.**
Your call.

In the upper right corner of the app.

Deployed **PROGRAM_ID** should update as well. (mock data as of now, since we didn't deploy to other networks)
See what else needs to be updated.

**Bounty: 250**

**Comment by imprfekt** [comment]
@aborzanovic Sorry for reopening this one, but we need a network indicator at all times (even when wallet connected). Reason being is we don't want user to accidentally use the wrong network to stream payments.

**Comment by aborzanovic** [comment]
@imprfekt, alright

- so should you be able to change the network while your wallet is connected?
  - if so, what happens when you switch the network - we automatically disconnect your wallet and start the wallet connection flow on the newly selected network?
- or should it just be a label and you have to disconnect in order to switch?

**Comment by imprfekt** [comment]
First scenario.

If possible to remain connected to the wallet and just switch the network -
perfect. But I don’t think that’s possible.
